// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALaIuErbr-b4zoDjc-QwJvRj87ASTxExs',
    appId: '1:205339221130:web:0096b51d0c0e1a52b9a173',
    messagingSenderId: '205339221130',
    projectId: 'refferaladminweb',
    authDomain: 'refferaladminweb.firebaseapp.com',
    storageBucket: 'refferaladminweb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjz5LxpKtCuTZu_yt9XbEoft0X83YXZho',
    appId: '1:205339221130:android:92d1944e7cead424b9a173',
    messagingSenderId: '205339221130',
    projectId: 'refferaladminweb',
    storageBucket: 'refferaladminweb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3Q11KmDC01Ws35k0yUqaRzLYAo-sCFQc',
    appId: '1:205339221130:ios:d9b2e41791bf3f0eb9a173',
    messagingSenderId: '205339221130',
    projectId: 'refferaladminweb',
    storageBucket: 'refferaladminweb.appspot.com',
    iosClientId: '205339221130-3fm0cnhcocnk1otisu69hk4ib1qev6d8.apps.googleusercontent.com',
    iosBundleId: 'com.example.referralAdminWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3Q11KmDC01Ws35k0yUqaRzLYAo-sCFQc',
    appId: '1:205339221130:ios:d9b2e41791bf3f0eb9a173',
    messagingSenderId: '205339221130',
    projectId: 'refferaladminweb',
    storageBucket: 'refferaladminweb.appspot.com',
    iosClientId: '205339221130-3fm0cnhcocnk1otisu69hk4ib1qev6d8.apps.googleusercontent.com',
    iosBundleId: 'com.example.referralAdminWeb',
  );
}
