import 'package:flutter/material.dart';
import 'package:referral_admin_web/View_models/ModelPendingReferalPartner.dart';
import 'package:referral_admin_web/View_models/ModelReferalPartners.dart';

List<ModelReferalPartners> referralPartnersList = [
  ModelReferalPartners(
      Name: "Adam Smith",
      Referrals: "03",
      JobsSold: "400",
      TotalInvoiced: "8000",
      AvgReferralInvoice: "435",
      editImage: "assets/images/edit.png",
      eyeIcon: Icons.remove_red_eye_outlined),
  ModelReferalPartners(
      Name: "Benjamin",
      Referrals: "03",
      JobsSold: "400",
      TotalInvoiced: "8000",
      AvgReferralInvoice: "435",
      editImage: "assets/images/edit.png",
      eyeIcon: Icons.remove_red_eye_outlined),
  ModelReferalPartners(
      Name: "Daniel Watson",
      Referrals: "03",
      JobsSold: "400",
      TotalInvoiced: "8000",
      AvgReferralInvoice: "435",
      editImage: "assets/images/edit.png",
      eyeIcon: Icons.remove_red_eye_outlined),
  ModelReferalPartners(
      Name: "Nicholas Warner",
      Referrals: "03",
      JobsSold: "400",
      TotalInvoiced: "8000",
      AvgReferralInvoice: "435",
      editImage: "assets/images/edit.png",
      eyeIcon: Icons.remove_red_eye_outlined),
  ModelReferalPartners(
      Name: "Nicholas Warner",
      Referrals: "44",
      JobsSold: "400",
      TotalInvoiced: "8000",
      AvgReferralInvoice: "435",
      editImage: "assets/images/edit.png",
      eyeIcon: Icons.remove_red_eye_outlined),
  ModelReferalPartners(
      Name: "Daniel Watson",
      Referrals: "03",
      JobsSold: "400",
      TotalInvoiced: "8000",
      AvgReferralInvoice: "435",
      editImage: "assets/images/edit.png",
      eyeIcon: Icons.remove_red_eye_outlined),
  ModelReferalPartners(
      Name: "Nicholas Warner",
      Referrals: "03",
      JobsSold: "400",
      TotalInvoiced: "8000",
      AvgReferralInvoice: "435",
      editImage: "assets/images/edit.png",
      eyeIcon: Icons.remove_red_eye_outlined),
  ModelReferalPartners(
      Name: "Nicholas Warner",
      Referrals: "44",
      JobsSold: "400",
      TotalInvoiced: "8000",
      AvgReferralInvoice: "435",
      editImage: "assets/images/edit.png",
      eyeIcon: Icons.remove_red_eye_outlined),
  ModelReferalPartners(
      Name: "Daniel Watson",
      Referrals: "03",
      JobsSold: "400",
      TotalInvoiced: "8000",
      AvgReferralInvoice: "435",
      editImage: "assets/images/edit.png",
      eyeIcon: Icons.remove_red_eye_outlined),
  ModelReferalPartners(
      Name: "Nicholas Warner",
      Referrals: "03",
      JobsSold: "400",
      TotalInvoiced: "8000",
      AvgReferralInvoice: "435",
      editImage: "assets/images/edit.png",
      eyeIcon: Icons.remove_red_eye_outlined),
  ModelReferalPartners(
      Name: "Nicholas Warner",
      Referrals: "44",
      JobsSold: "400",
      TotalInvoiced: "8000",
      AvgReferralInvoice: "435",
      editImage: "assets/images/edit.png",
      eyeIcon: Icons.remove_red_eye_outlined),
  ModelReferalPartners(
      Name: "Daniel Watson",
      Referrals: "03",
      JobsSold: "400",
      TotalInvoiced: "8000",
      AvgReferralInvoice: "435",
      editImage: "assets/images/edit.png",
      eyeIcon: Icons.remove_red_eye_outlined),
  ModelReferalPartners(
      Name: "Nicholas Warner",
      Referrals: "03",
      JobsSold: "400",
      TotalInvoiced: "8000",
      AvgReferralInvoice: "435",
      editImage: "assets/images/edit.png",
      eyeIcon: Icons.remove_red_eye_outlined),
  ModelReferalPartners(
      Name: "Nicholas Warner",
      Referrals: "44",
      JobsSold: "400",
      TotalInvoiced: "8000",
      AvgReferralInvoice: "435",
      editImage: "assets/images/edit.png",
      eyeIcon: Icons.remove_red_eye_outlined),
  ModelReferalPartners(
      Name: "Daniel Watson",
      Referrals: "03",
      JobsSold: "400",
      TotalInvoiced: "8000",
      AvgReferralInvoice: "435",
      editImage: "assets/images/edit.png",
      eyeIcon: Icons.remove_red_eye_outlined),
  ModelReferalPartners(
      Name: "Nicholas Warner",
      Referrals: "03",
      JobsSold: "400",
      TotalInvoiced: "8000",
      AvgReferralInvoice: "435",
      editImage: "assets/images/edit.png",
      eyeIcon: Icons.remove_red_eye_outlined),
  ModelReferalPartners(
      Name: "Nicholas Warner",
      Referrals: "44",
      JobsSold: "400",
      TotalInvoiced: "8000",
      AvgReferralInvoice: "435",
      editImage: "assets/images/edit.png",
      eyeIcon: Icons.remove_red_eye_outlined),
  ModelReferalPartners(
      Name: "Daniel Watson",
      Referrals: "03",
      JobsSold: "400",
      TotalInvoiced: "8000",
      AvgReferralInvoice: "435",
      editImage: "assets/images/edit.png",
      eyeIcon: Icons.remove_red_eye_outlined),
  ModelReferalPartners(
      Name: "Nicholas Warner",
      Referrals: "03",
      JobsSold: "400",
      TotalInvoiced: "8000",
      AvgReferralInvoice: "435",
      editImage: "assets/images/edit.png",
      eyeIcon: Icons.remove_red_eye_outlined),
  ModelReferalPartners(
      Name: "Nicholas Warner",
      Referrals: "44",
      JobsSold: "400",
      TotalInvoiced: "8000",
      AvgReferralInvoice: "435",
      editImage: "assets/images/edit.png",
      eyeIcon: Icons.remove_red_eye_outlined),
  ModelReferalPartners(
      Name: "Daniel Watson",
      Referrals: "03",
      JobsSold: "400",
      TotalInvoiced: "8000",
      AvgReferralInvoice: "435",
      editImage: "assets/images/edit.png",
      eyeIcon: Icons.remove_red_eye_outlined),
  ModelReferalPartners(
      Name: "Nicholas Warner",
      Referrals: "03",
      JobsSold: "400",
      TotalInvoiced: "8000",
      AvgReferralInvoice: "435",
      editImage: "assets/images/edit.png",
      eyeIcon: Icons.remove_red_eye_outlined),
  ModelReferalPartners(
      Name: "Nicholas Warner",
      Referrals: "44",
      JobsSold: "400",
      TotalInvoiced: "8000",
      AvgReferralInvoice: "435",
      editImage: "assets/images/edit.png",
      eyeIcon: Icons.remove_red_eye_outlined),
  ModelReferalPartners(
      Name: "Daniel Watson",
      Referrals: "03",
      JobsSold: "400",
      TotalInvoiced: "8000",
      AvgReferralInvoice: "435",
      editImage: "assets/images/edit.png",
      eyeIcon: Icons.remove_red_eye_outlined),
  ModelReferalPartners(
      Name: "Nicholas Warner",
      Referrals: "03",
      JobsSold: "400",
      TotalInvoiced: "8000",
      AvgReferralInvoice: "435",
      editImage: "assets/images/edit.png",
      eyeIcon: Icons.remove_red_eye_outlined),
  ModelReferalPartners(
      Name: "Nicholas Warner",
      Referrals: "44",
      JobsSold: "400",
      TotalInvoiced: "8000",
      AvgReferralInvoice: "435",
      editImage: "assets/images/edit.png",
      eyeIcon: Icons.remove_red_eye_outlined),
  ModelReferalPartners(
      Name: "Daniel Watson",
      Referrals: "03",
      JobsSold: "400",
      TotalInvoiced: "8000",
      AvgReferralInvoice: "435",
      editImage: "assets/images/edit.png",
      eyeIcon: Icons.remove_red_eye_outlined),
  ModelReferalPartners(
      Name: "Nicholas Warner",
      Referrals: "03",
      JobsSold: "400",
      TotalInvoiced: "8000",
      AvgReferralInvoice: "435",
      editImage: "assets/images/edit.png",
      eyeIcon: Icons.remove_red_eye_outlined),
  ModelReferalPartners(
      Name: "Nicholas Warner",
      Referrals: "44",
      JobsSold: "400",
      TotalInvoiced: "8000",
      AvgReferralInvoice: "435",
      editImage: "assets/images/edit.png",
      eyeIcon: Icons.remove_red_eye_outlined),
  ModelReferalPartners(
      Name: "Daniel Watson",
      Referrals: "03",
      JobsSold: "400",
      TotalInvoiced: "8000",
      AvgReferralInvoice: "435",
      editImage: "assets/images/edit.png",
      eyeIcon: Icons.remove_red_eye_outlined),
  ModelReferalPartners(
      Name: "Nicholas Warner",
      Referrals: "03",
      JobsSold: "400",
      TotalInvoiced: "8000",
      AvgReferralInvoice: "435",
      editImage: "assets/images/edit.png",
      eyeIcon: Icons.remove_red_eye_outlined),
  ModelReferalPartners(
      Name: "Nicholas Warner",
      Referrals: "44",
      JobsSold: "400",
      TotalInvoiced: "8000",
      AvgReferralInvoice: "435",
      editImage: "assets/images/edit.png",
      eyeIcon: Icons.remove_red_eye_outlined),
  ModelReferalPartners(
      Name: "Daniel Watson",
      Referrals: "03",
      JobsSold: "400",
      TotalInvoiced: "8000",
      AvgReferralInvoice: "435",
      editImage: "assets/images/edit.png",
      eyeIcon: Icons.remove_red_eye_outlined),
  ModelReferalPartners(
      Name: "Nicholas Warner",
      Referrals: "03",
      JobsSold: "400",
      TotalInvoiced: "8000",
      AvgReferralInvoice: "435",
      editImage: "assets/images/edit.png",
      eyeIcon: Icons.remove_red_eye_outlined),
  ModelReferalPartners(
      Name: "Nicholas Warner",
      Referrals: "44",
      JobsSold: "400",
      TotalInvoiced: "8000",
      AvgReferralInvoice: "435",
      editImage: "assets/images/edit.png",
      eyeIcon: Icons.remove_red_eye_outlined),
  ModelReferalPartners(
      Name: "Daniel Watson",
      Referrals: "03",
      JobsSold: "400",
      TotalInvoiced: "8000",
      AvgReferralInvoice: "435",
      editImage: "assets/images/edit.png",
      eyeIcon: Icons.remove_red_eye_outlined),
  ModelReferalPartners(
      Name: "Nicholas Warner",
      Referrals: "03",
      JobsSold: "400",
      TotalInvoiced: "8000",
      AvgReferralInvoice: "435",
      editImage: "assets/images/edit.png",
      eyeIcon: Icons.remove_red_eye_outlined),
  ModelReferalPartners(
      Name: "Nicholas Warner",
      Referrals: "44",
      JobsSold: "400",
      TotalInvoiced: "8000",
      AvgReferralInvoice: "435",
      editImage: "assets/images/edit.png",
      eyeIcon: Icons.remove_red_eye_outlined),
  ModelReferalPartners(
      Name: "Daniel Watson",
      Referrals: "44",
      JobsSold: "400",
      TotalInvoiced: "8000",
      AvgReferralInvoice: "435",
      editImage: "assets/images/edit.png",
      eyeIcon: Icons.remove_red_eye_outlined),
  ModelReferalPartners(
      Name: "Benjamin",
      Referrals: "33",
      JobsSold: "400",
      TotalInvoiced: "8000",
      AvgReferralInvoice: "435",
      editImage: "assets/images/edit.png",
      eyeIcon: Icons.remove_red_eye_outlined),
  ModelReferalPartners(
      Name: "Adam Smith",
      Referrals: "222",
      JobsSold: "400",
      TotalInvoiced: "8000",
      AvgReferralInvoice: "435",
      editImage: "assets/images/edit.png",
      eyeIcon: Icons.remove_red_eye_outlined),
  ModelReferalPartners(
      Name: "Adam Smith",
      Referrals: "54",
      JobsSold: "400",
      TotalInvoiced: "8000",
      AvgReferralInvoice: "435",
      editImage: "assets/images/edit.png",
      eyeIcon: Icons.remove_red_eye_outlined),
  ModelReferalPartners(
      Name: "Nicholas Warner",
      Referrals: "02",
      JobsSold: "400",
      TotalInvoiced: "8000",
      AvgReferralInvoice: "435",
      editImage: "assets/images/edit.png",
      eyeIcon: Icons.remove_red_eye_outlined),
  ModelReferalPartners(
      Name: "Daniel Watson",
      Referrals: "22",
      JobsSold: "400",
      TotalInvoiced: "8000",
      AvgReferralInvoice: "435",
      editImage: "assets/images/edit.png",
      eyeIcon: Icons.remove_red_eye_outlined),
  ModelReferalPartners(
      Name: "Benjamin",
      Referrals: "12",
      JobsSold: "400",
      TotalInvoiced: "8000",
      AvgReferralInvoice: "435",
      editImage: "assets/images/edit.png",
      eyeIcon: Icons.remove_red_eye_outlined),
];
List<ModelPendingReferalPartners> pendingReferralPartnersList = [
  ModelPendingReferalPartners(
    Name: "Adam Smith",
    ReferralPartner: "Roberto",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Initech ",
    Email: "as it.png",
    Action: "asset dit.png",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Daniel Watson",
    ReferralPartner: "Joe Goldberg",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Hooli (Silicon Valley)",
    Email: "assets/imag ",
    Action: "assets ",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Daniel Watson",
    ReferralPartner: "Joe Goldberg",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Hooli (Silicon Valley)",
    Email: "assets/imag ",
    Action: "assets ",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Daniel Watson",
    ReferralPartner: "Joe Goldberg",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Hooli (Silicon Valley)",
    Email: "assets/imag ",
    Action: "assets ",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Daniel Watson",
    ReferralPartner: "Joe Goldberg",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Hooli (Silicon Valley)",
    Email: "assets/imag ",
    Action: "assets ",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Daniel Watson",
    ReferralPartner: "Joe Goldberg",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Hooli (Silicon Valley)",
    Email: "assets/imag ",
    Action: "assets ",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Daniel Watson",
    ReferralPartner: "Joe Goldberg",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Hooli (Silicon Valley)",
    Email: "assets/imag ",
    Action: "assets ",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Daniel Watson",
    ReferralPartner: "Joe Goldberg",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Hooli (Silicon Valley)",
    Email: "assets/imag ",
    Action: "assets ",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Daniel Watson",
    ReferralPartner: "Joe Goldberg",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Hooli (Silicon Valley)",
    Email: "assets/imag ",
    Action: "assets ",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Daniel Watson",
    ReferralPartner: "Joe Goldberg",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Hooli (Silicon Valley)",
    Email: "assets/imag ",
    Action: "assets ",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Daniel Watson",
    ReferralPartner: "Joe Goldberg",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Hooli (Silicon Valley)",
    Email: "assets/imag ",
    Action: "assets ",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Daniel Watson",
    ReferralPartner: "Joe Goldberg",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Hooli (Silicon Valley)",
    Email: "assets/imag ",
    Action: "assets ",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Daniel Watson",
    ReferralPartner: "Joe Goldberg",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Hooli (Silicon Valley)",
    Email: "assets/imag ",
    Action: "assets ",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Daniel Watson",
    ReferralPartner: "Joe Goldberg",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Hooli (Silicon Valley)",
    Email: "assets/imag ",
    Action: "assets ",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Daniel Watson",
    ReferralPartner: "Joe Goldberg",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Hooli (Silicon Valley)",
    Email: "assets/imag ",
    Action: "assets ",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Daniel Watson",
    ReferralPartner: "Joe Goldberg",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Hooli (Silicon Valley)",
    Email: "assets/imag ",
    Action: "assets ",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Daniel Watson",
    ReferralPartner: "Joe Goldberg",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Hooli (Silicon Valley)",
    Email: "assets/imag ",
    Action: "assets ",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Daniel Watson",
    ReferralPartner: "Joe Goldberg",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Hooli (Silicon Valley)",
    Email: "assets/imag ",
    Action: "assets ",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Daniel Watson",
    ReferralPartner: "Joe Goldberg",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Hooli (Silicon Valley)",
    Email: "assets/imag ",
    Action: "assets ",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Daniel Watson",
    ReferralPartner: "Joe Goldberg",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Hooli (Silicon Valley)",
    Email: "assets/imag ",
    Action: "assets ",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Daniel Watson",
    ReferralPartner: "Joe Goldberg",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Hooli (Silicon Valley)",
    Email: "assets/imag ",
    Action: "assets ",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Daniel Watson",
    ReferralPartner: "Joe Goldberg",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Hooli (Silicon Valley)",
    Email: "assets/imag ",
    Action: "assets ",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Daniel Watson",
    ReferralPartner: "Joe Goldberg",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Hooli (Silicon Valley)",
    Email: "assets/imag ",
    Action: "assets ",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Daniel Watson",
    ReferralPartner: "Joe Goldberg",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Hooli (Silicon Valley)",
    Email: "assets/imag ",
    Action: "assets ",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Daniel Watson",
    ReferralPartner: "Joe Goldberg",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Hooli (Silicon Valley)",
    Email: "assets/imag ",
    Action: "assets ",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Daniel Watson",
    ReferralPartner: "Joe Goldberg",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Hooli (Silicon Valley)",
    Email: "assets/imag ",
    Action: "assets ",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Daniel Watson",
    ReferralPartner: "Joe Goldberg",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Hooli (Silicon Valley)",
    Email: "assets/imag ",
    Action: "assets ",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Daniel Watson",
    ReferralPartner: "Joe Goldberg",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Hooli (Silicon Valley)",
    Email: "assets/imag ",
    Action: "assets ",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Daniel Watson",
    ReferralPartner: "Joe Goldberg",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Hooli (Silicon Valley)",
    Email: "assets/imag ",
    Action: "assets ",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Daniel Watson",
    ReferralPartner: "Joe Goldberg",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Hooli (Silicon Valley)",
    Email: "assets/imag ",
    Action: "assets ",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Daniel Watson",
    ReferralPartner: "Joe Goldberg",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Hooli (Silicon Valley)",
    Email: "assets/imag ",
    Action: "assets ",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Daniel Watson",
    ReferralPartner: "Joe Goldberg",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Hooli (Silicon Valley)",
    Email: "assets/imag ",
    Action: "assets ",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Daniel Watson",
    ReferralPartner: "Joe Goldberg",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Hooli (Silicon Valley)",
    Email: "assets/imag ",
    Action: "assets ",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Daniel Watson",
    ReferralPartner: "Joe Goldberg",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Hooli (Silicon Valley)",
    Email: "assets/imag ",
    Action: "assets ",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Daniel Watson",
    ReferralPartner: "Joe Goldberg",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Hooli (Silicon Valley)",
    Email: "assets/imag ",
    Action: "assets ",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Daniel Watson",
    ReferralPartner: "Joe Goldberg",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Hooli (Silicon Valley)",
    Email: "assets/imag ",
    Action: "assets ",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Daniel Watson",
    ReferralPartner: "Joe Goldberg",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Hooli (Silicon Valley)",
    Email: "assets/imag ",
    Action: "assets ",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Daniel Watson",
    ReferralPartner: "Joe Goldberg",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Hooli (Silicon Valley)",
    Email: "assets/imag ",
    Action: "assets ",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Daniel Watson",
    ReferralPartner: "Joe Goldberg",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Hooli (Silicon Valley)",
    Email: "assets/imag ",
    Action: "assets ",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Daniel Watson",
    ReferralPartner: "Joe Goldberg",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Hooli (Silicon Valley)",
    Email: "assets/imag ",
    Action: "assets ",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Daniel Watson",
    ReferralPartner: "Joe Goldberg",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Hooli (Silicon Valley)",
    Email: "assets/imag ",
    Action: "assets ",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "Jack Brown",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Umbrella Corporation",
    Email: " images ",
    Action: "ng",
  ),
  ModelPendingReferalPartners(
    Name: "Daniel Watson",
    ReferralPartner: "Joe Goldberg",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Hooli (Silicon Valley)",
    Email: "assets/imag ",
    Action: "assets ",
  ),
  ModelPendingReferalPartners(
    Name: "Nicholas Warner",
    ReferralPartner: "Watson",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Vehement Capital.",
    Email: " edit.png",
    Action: "a t.png",
  ),
  ModelPendingReferalPartners(
    Name: "Adam Smith",
    ReferralPartner: "Nicolaus ",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Soylent Corp.",
    Email: " .png",
    Action: "assetss.png",
  ),
  ModelPendingReferalPartners(
    Name: "Benjamin",
    ReferralPartner: "James Bond",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Globex Corporation ",
    Email: " / / .png",
    Action: " edit.png",
  ),
  ModelPendingReferalPartners(
    Name: "Daniel Watson",
    ReferralPartner: "Oliver",
    PhoneNumber: "+1-344-9876123",
    JobTitle: "Designation here",
    Company: "Massive Dynamic ",
    Email: " edit.png",
    Action: " edit.png",
  ),
];
